### PR TITLE
changes for consistency w/ cice6

### PR DESCRIPTION
**Pull request by DeniseWorthen**
- Issue #24 

- Issue #23 

Related S2S PR: [#152](https://github.com/ufs-community/ufs-s2s-model/pull/152)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
New baselines have been created on hera,orion and dell (develop-20200731). 

The impact of changing the freezing temperature is shown below. Both the current develop and this branch were run for 5d in the benchmark RT. The left panel shows the difference in congelation ice growth rate at the end of 5days; on the right is the the difference in freezing temperature between assuming a constant Tf=-1.836 and using the surface salinity-dependent freezing temperature. Greater congelation growth is generally correlated with warmer (less negative) freezing temperatures. Areas of low surface salinity associated with river runoff show large differences in freezing temperature.

ice_diff

**Comment by DeniseWorthen** [comment]
I've created the baseline on dell, but my nemspara account access does not seem to be working ('id' shows I should have it). Would one of you please move the baseline on dell to develop-20200731 (from /gpfs/dell2/stmp/Denise.Worthen/S2S_RT/REGRESSION_TEST). 

@MinsukJi-NOAA: The new baseline (develop-20200731) is in /work/noaa/stmp/dworthen/stmp/dworthen/S2S_RT/REGRESSION_TEST_INTEL

Thanks!

**Comment by junwang-noaa** [comment]
Denise,

Sorry, I am not sure if some of your baseline is scrubbed. I only see:

$ ls /gpfs/dell2/stmp/Denise.Worthen/S2S_RT/REGRESSION_TEST
BM_IC  CPL_FIX  FV3_input_data384

**Comment by DeniseWorthen** [comment]
Yes, I guess it got scrubbed already. I will regenerate on Dell. 

To move the baseline on Dell, I tried the same thing as I use on Hera: sudo su - emc.nemspara. Is there a different procedure on Dell? I am asked for a password when logging into Dell, so I think I do have the role account access.

**Comment by junwang-noaa** [comment]
On dell, please try: sudo -u emc.nemspara bash --login

**Comment by DeniseWorthen** [comment]
Thanks. I'm able to move the baseline on Dell now.

**Comment by DeniseWorthen** [comment]
New baselines have been created and moved into place on all platforms.

**Review by junwang-noaa — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Pull request merged**
